### ISSUE TITLE
UI design in main application

### ISSUE THREAD

**Issue by bluespada** [bluespada/nwhale#1]
# UI design in main application

for now look like this :

![Image](https://github.com/bluespada/nwhale/assets/55633183/18a9e5bf-b66d-45d3-b896-f847621fd21f)

### TODO:

- [ ] add menu tab bar on opened documents noted.
- [ ] re arange items tab bars
- [ ] users enable to close tab menu
